# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 11:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battalion',
            fields=[
                ('name', models.CharField(max_length=250, verbose_name='Name of Battalion')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('slug', models.SlugField(editable=False, null=True)),
            ],
            options={
                'db_table': 'battalions',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('unit', 'unit')], max_length=10)),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('req_datetime', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField()),
                ('packet_type', models.IntegerField()),
                ('source_addr', models.BigIntegerField()),
                ('dest_addr', models.BigIntegerField()),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Geospace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'geospaces',
            },
        ),
        migrations.CreateModel(
            name='Intrusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('ignore', models.BooleanField(default=False)),
                ('attempts', models.IntegerField()),
            ],
            options={
                'db_table': 'intrusion',
            },
        ),
        migrations.CreateModel(
            name='Morcha',
            fields=[
                ('name', models.CharField(max_length=250, verbose_name='name of morcha')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=16, null=True)),
                ('slug', models.SlugField(editable=False, null=True)),
                ('geospace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='slider.Geospace')),
            ],
            options={
                'db_table': 'morchas',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('name', models.CharField(max_length=250, verbose_name='name of post')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('slug', models.SlugField(editable=False, null=True)),
                ('battalion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='slider.Battalion')),
                ('geospace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='slider.Geospace')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.AddField(
            model_name='morcha',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morchas', to='slider.Post'),
        ),
        migrations.AddField(
            model_name='intrusion',
            name='morcha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slider.Morcha'),
        ),
        migrations.AddField(
            model_name='device',
            name='morcha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='slider.Morcha'),
        ),
        migrations.AddField(
            model_name='battalion',
            name='geospace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='slider.Geospace'),
        ),
    ]
